modules/ROOT/pages/jupyter.adoc

This PR is to make it easier for people to decide which option they should use as when they want to use Vantage from a Jupyter notebook.

Update jupyter.adoc - improve recommendation for different options

---

modules/ROOT/nav.adoc
modules/ROOT/pages/local.jupyter.hub.adoc
supplemental_ui/partials/footer-scripts.hbs

Local jupyter cluster

---

modules/ROOT/nav.adoc
modules/ROOT/pages/timeseries.adoc

Added new timeseries.adoc with time series analysis and modified the nav.adoc as well

Time series functions tutorial

---

supplemental_ui/partials/landing.hbs

update landing to include ModelOps tiles for GIT and BYOM

update landing to include ModelOps tiles

---

modules/mule-teradata-connector/pages/index.adoc
modules/mule-teradata-connector/pages/reference.adoc
modules/mule-teradata-connector/pages/release-notes.adoc

Add user-guide, reference, and release notes for mule-teradata-connector

Add documentations for mule-teradata-connector

---

modules/mule-teradata-connector/pages/index.adoc
modules/mule-teradata-connector/pages/reference.adoc
modules/mule-teradata-connector/pages/release-notes.adoc

- Add metadata, keywords
- Update list of features
- Update features for release notes
- Add Examples for Index page

Update documentation for mule-teradata-connector

---

modules/ROOT/pages/create-parquet-files-in-object-storage.adoc
modules/ROOT/pages/fastload.adoc
modules/ROOT/pages/jdbc.adoc
modules/ROOT/pages/mule.jdbc.example.adoc
modules/ROOT/pages/nos.adoc
modules/ROOT/pages/odbc.ubuntu.adoc
modules/ROOT/pages/perform-time-series-analysis-using-teradata-vantage.adoc
modules/ROOT/pages/segment.adoc
modules/ROOT/pages/sto.adoc
modules/ROOT/partials/vantage_clearscape_analytics
modules/business-intelligence/pages/create-stunning-visualizations-in-power-bi-using-data-from-teradata-vantage.adoc
modules/cloud-guides/pages/connect-azure-data-share-to-teradata-vantage.adoc
modules/cloud-guides/pages/integrate-teradata-vantage-to-salesforce-using-amazon-appflow.adoc
modules/cloud-guides/pages/integrate-teradata-vantage-with-google-cloud-data-catalog.adoc
modules/cloud-guides/pages/sagemaker-with-teradata-vantage.adoc
modules/cloud-guides/pages/use-teradata-vantage-with-azure-machine-learning-studio.adoc
modules/modelops/pages/deploy-and-monitor-machine-learning-models-with-teradata-modelops-and-byom.adoc
modules/modelops/pages/deploy-and-monitor-machine-learning-models-with-teradata-modelops-and-git.adoc
modules/modelops/pages/using-feast-feature-store-with-teradata-vantage.adoc
modules/mule-teradata-connector/pages/index.adoc
modules/other-integrations/pages/configure-a-teradata-vantage-connection-in-dbeaver.adoc
modules/other-integrations/pages/integrate-teradata-vantage-with-knime.adoc
modules/tools-and-utilities/pages/run-bulkloads-efficiently-with-teradata-parallel-transporter.adoc

This branch contains the change of all references that mention access to Vantage through a VM instance to access to Vantage through Clearscape Analytics.

Changing References to VM Vantage Instance to Clearscape Vantage access

---

README.md

Added instructions to build website in windows on the Readme, also added instructions to serve the website locally.

Add Windows Website Building Instructions to Readme

---

modules/ROOT/pages/jupyter.adoc
modules/ROOT/pages/local.jupyter.hub.adoc
modules/ROOT/partials/jupyter_notebook_clearscape_analytics_note.adoc
modules/cloud-guides/pages/integrate-teradata-jupyter-extensions-with-google-vertex-ai.adoc
modules/cloud-guides/pages/integrate-teradata-jupyter-extensions-with-sagemaker.adoc

In this commit we are adding two notes to the Jupyter Notebooks related quickstarts regarding the possibility of using clearscape analytics.

Reference clearscape in jupyter quickstarts

---

README.md
modules/ROOT/pages/jupyter.adoc
modules/ROOT/pages/ml.adoc
modules/modelops/pages/deploy-and-monitor-machine-learning-models-with-teradata-modelops-and-byom.adoc
modules/modelops/pages/deploy-and-monitor-machine-learning-models-with-teradata-modelops-and-git.adoc

Changed all references to quickstarts as noun, references in URLs and URL related situations remain

Changed Noun References to Quickstarts

---

modules/ROOT/nav.adoc
modules/ROOT/pages/advanced-dbt.adoc

This branch contains the new quickstart for advanced dbt it modifies the modules/root/pages  and the nav to include it in the navigation.

Advanced dbt

---

modules/ROOT/partials/vantage_clearscape_analytics.adoc

This modifies the partial document to add tracking to clearscape mentions

added tracking

---

modules/ROOT/pages/geojson-to-vantage.adoc

Quickstart describing how to load and use GeoJSON documents to support geospatial analytics.

Created new QuickStart for GeoJson load and usage

---

modules/business-intelligence/pages/create-stunning-visualizations-in-power-bi-using-data-from-teradata-vantage.adoc

Link to community specific forum.

Link to community on Readme

---

modules/query-service/pages/send-queries-using-rest-api.adoc

This makes clarification on working with query service in clearscape analytics experience.

added system identification for CSAE in Query Service

---

modules/ROOT/nav.adoc
modules/ROOT/pages/teradatasql.adoc

@adamtwo @Daniel-Itzul Please review the quickstart for `teradatasql` Python database driver for Vantage.

quickstart for teradatasql python database driver

---

modules/ROOT/pages/install-teradata-studio-on-mac-m1-m2.adoc

Updated with latest version and type of processor with latest versions

---

modules/ROOT/pages/mule.jdbc.example.adoc

Connector updated in order to make compatible with maven installs

Updated the quickstart regarding mulesoft connector

---

modules/ROOT/pages/local.jupyter.hub.adoc

fix 2 broken links for teradataml and tdplyr in local.jupyter.hub.adoc

fix broken links in local.jupyter.hub.adoc

---

.vscode/settings.json
modules/ROOT/pages/mule.jdbc.example.adoc

added event mulesoft

---

supplemental_ui/partials/header-content.hbs

@adamtwo I have added the sql-formatter function in the header-content.hbs partial

header-content partial updated with sql-formatter code

---

supplemental_ui/js/redirect.js

Reverts Teradata/quickstarts#215

Revert "test redirect"

---

supplemental_ui/partials/lang/navbar-en.hbs
supplemental_ui/partials/lang/navbar-es.hbs
supplemental_ui/partials/lang/navbar-ja.hbs

Update CTA text to - Try for free

---

generate-redirects.js
static/airflow/airflow-azure-to-teradata-transfer-operator-doc.html

Adding correct redirect for Azure Airflow doc

feat(redirects): adding correct airflow redirect

---

generate-redirects.js
static/ai-unlimited/deploy-ai-unlimited-aws-cloudformation.html
static/ai-unlimited/install-ai-unlimited-workspaces-docker.html
static/ja/ai-unlimited/deploy-ai-unlimited-aws-cloudformation.html
static/ja/ai-unlimited/install-ai-unlimited-workspaces-docker.html

Adjusting redirects for AI unlimited pages
- https://quickstarts.teradata.com/ai-unlimited/install-ai-unlimited-workspaces-docker.html -> https://developers.teradata.com/ai-unlimited/resources/quickstart/run-ai-unlimited-jupyterlab-docker/
- https://quickstarts.teradata.com/ai-unlimited/deploy-ai-unlimited-aws-cloudformation.html -> https://developers.teradata.com/ai-unlimited/install-ai-unlimited/deploy-manager-aws-console/

fix(ai-unlimited): fixing incorrect redirect URL
